# SERVICE TYPE: GetGeoStructure
# ------------------------------------------------------------------------------
# This service return a geostructure list (lat, lon, alt) stored in the geostructures node

---
bool success                    # whether the geofence has been set or not
geostructures/Geostructure[] geostructure_list   # geofences stored in memory
# ------------------------------------------------------------------------------
