# SERVICE TYPE: SetGeostructure
# ------------------------------------------------------------------------------
# This service creates a geoStructure (lat, lon, alt) to set in geostructures node

geostructures/Geostructure geostructure  # geostructure to set
---
bool success                # whether the geoStructure has been set or not
# ------------------------------------------------------------------------------
